name = "mcp-orchestrator"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "mcp-orchestrator-prod"

[env.staging]
name = "mcp-orchestrator-staging"

# D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "mcp-orchestrator-db"
database_id = ""

[[d1_databases.env.production]]
binding = "DB"
database_name = "mcp-orchestrator-db-prod"
database_id = ""

[[d1_databases.env.staging]]
binding = "DB"
database_name = "mcp-orchestrator-db-staging"
database_id = ""

# R2 Storage bindings
[[r2_buckets]]
binding = "R2"
bucket_name = "mcp-orchestrator-storage"

[[r2_buckets.env.production]]
binding = "R2"
bucket_name = "mcp-orchestrator-storage-prod"

[[r2_buckets.env.staging]]
binding = "R2"
bucket_name = "mcp-orchestrator-storage-staging"

# Queue bindings for async operations
[[queues.producers]]
binding = "TASK_QUEUE"
queue = "mcp-orchestrator-tasks"

[[queues.consumers]]
queue = "mcp-orchestrator-tasks"
max_batch_size = 10
max_batch_timeout = 30

# Environment variables
[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "info"

[env.production.vars]
ENVIRONMENT = "production"

[env.staging.vars]
ENVIRONMENT = "staging"

# Security headers
[build]
command = "npm run build"