name = "mcp-orchestrator"
main = "./dist/index.js"
compatibility_date = "2024-04-05"

[[d1_databases]]
binding = "DB"
database_name = "mcp"
database_id = "mcp"
migrations_dir = "../../migrations"

[dev]
port = 8787

[build]
command = "pnpm --filter worker run compile"
