name: Deploy Worker
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ${{ github.event.pull_request.head.repo.full_name && github.event.pull_request.head.repo.full_name != github.repository && 'ubuntu-latest' || fromJSON('["self-hosted","Linux","X64","proxmox-actions"]') }}
    steps:
      - run: echo "Deploying worker"
